### ISSUE TITLE
Anyway to develop in different platform?

### ISSUE THREAD

**Issue by xiekeyi98** [zaypen/game-of-life#1]
I know your project is build in MacOS , but I want to use the orther platform to develop it .
I know the SFML Library could support defferent platform.

I was wondering if you could tell me , how to solve this problem ? Could you plz give me some word keys so that I can learn it .

-------

我看到您的项目是使用MacOS构建的，我也了解到您所使用的库是基于SFML的，而SFML是一个跨平台库。

我猜github上应该有解决不同平台之间开发需要链接不同的库的问题。请问您能否提供一些关键词，我想去搜索一下这方面的解决方法。

冒昧打扰您，非常感谢。

**Comment by zaypen** [comment]
@xiekeyi98 构建和Github是无关的，参考一下我更新后的[README.md](../blob/master/README.md)。

**Comment by xiekeyi98** [comment]
非常感谢~
